### PR TITLE
Add Amperfy to list of participating clients

### PR DESCRIPTION
**Pull request by gabeklavans**
It's a very well made Subsonic-compatible client (I tested it with Gonic)

### CODE REVIEW

**Comment by dweymouth** [comment]
Has Amperfy added any features enabled by the OpenSubsonic API extensions? There are a lot of great Subsonic clients out there that aren't (yet at least) OpenSubsonic clients.

**Comment by gabeklavans** [comment]
> Has Amperfy added any features enabled by the OpenSubsonic API extensions? There are a lot of great Subsonic clients out there that aren't (yet at least) OpenSubsonic clients.

Hmm good point. I didn't check that it actually used the OpenSubsonic extensions. I can check on that later, but now that I'm thinking about it, I'm doubtful.

**Comment by deluan** [comment]
This list is for the client and servers that have a commitment with proposing, discussing and implementing new features to the Subsonic API. As @dweymouth mentioned, I think Amperfy has not added any OpenSubsonic features yet (I can be wrong).

I invited @BLeeEZ (Amperfy author) [a while ago](https://github.com/BLeeEZ/amperfy/discussions/187), maybe they can consider joining our "consortium" now?

**Comment by BLeeEZ** [comment]
Hi, that's correct I a haven't implemented OpenSubsonic features yet.
I am planing to support it when working on Lyrics feature for Amperfy.

**Comment by BLeeEZ** [comment]
Amperfy now supports OpenSubsonic https://github.com/BLeeEZ/amperfy/commit/1723445f5721dfae13b3b5e500469390559e5833.  Amperfy checks for OpenSubsonicExtensions "songLyrics" support and then uses the OpenSubsonic "getLyricsBySongId" action.

**Review by deluan — APPROVED** [review]

**Review by dweymouth — APPROVED** [review]

**Comment by deluan** [comment]
Hey @BLeeEZ wanna join the OpenSubsonic organization? That way you become an approver for PRs that add functionality to the specification.

**Comment by BLeeEZ** [comment]
> Hey @BLeeEZ wanna join the OpenSubsonic organization? That way you become an approver for PRs that add functionality to the specification.

Thank you for the invite. Sounds interesting and I would be happy to join.

**Review by Tolriq — APPROVED** [review]

**Pull request merged**
