### PR TITLE
Document Stream endpoint behavior

### PR DESCRIPTION
**Pull request by Tolriq**
https://github.com/opensubsonic/open-subsonic-api/discussions/22 

Stream endpoint access must not count as playcount.

### CODE REVIEW

**Comment by Tolriq** [comment]
As discussed in https://github.com/opensubsonic/open-subsonic-api/discussions/22 (Top voted)

If you have not changed your mind, please add your reviews for merge.

**Review by sentriz — APPROVED** [review]
makes sense to me

**Review by ghenry22 — APPROVED** [review]
As per discussion, this is how navidrome already works and it’s a sensible change to have better control over playcount data quality.

anyone the records plays with navidrome will already work with this change.  Those that do not will simply have to add a call to the scrobble endpoint and remove any options client side to “scrobble to lastfm” as scrobbles will only go to the subsonic server.  Subsonic servers will have to implement an option to sync to lastfm or other external integrations.  Again Navidrome is a good example of this already well implemented in the server side.

**Review by epoupon — APPROVED** [review]

**Comment by Tolriq** [comment]
So merging since it was debated earlier too and largely voted.

**Pull request merged**
